# Generated by Django 4.1.4 on 2023-07-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='descriptions',
            field=models.TextField(default=''),
        ),
    ]
