# Generated by Django 4.1.4 on 2023-07-22 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_internship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='usno',
            new_name='usn',
        ),
    ]
